// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String coreCall({required String request}) =>
    RustLib.instance.api.crateApiSurfacesCoreCall(request: request);

Uint8List coreBytes({required String request}) =>
    RustLib.instance.api.crateApiSurfacesCoreBytes(request: request);

String opsCall({required String request}) =>
    RustLib.instance.api.crateApiSurfacesOpsCall(request: request);

String opsStart({required String request}) =>
    RustLib.instance.api.crateApiSurfacesOpsStart(request: request);

String opsPoll({required String id}) =>
    RustLib.instance.api.crateApiSurfacesOpsPoll(id: id);

String opsCancel({required String id}) =>
    RustLib.instance.api.crateApiSurfacesOpsCancel(id: id);
